title: "jormungandr1105's site"
tagline: "A place to log my misadventures with technology"
description: "A place to log my misadventures with technology"
github_username: jormungandr1105
baseurl: "/"
url: "https://jormungandr1105.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  
remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
